
openapi: 3.0.0
info:
  description:
    # Arquitectura de Información
    Proyecto Reconocimiento de Materiales de Iguala
  version: 1.0.0
  title: Arquitectura de Información RMI
  contact:
    name: Encargados de proyecto
    email: cvillegas@rimsamex.com
   
paths:
  /pet:
    parameters:
      - name: Accept-Language
        in: header
        description: "The language you prefer for messages. Supported values are en-AU, en-CA, en-GB, en-US"
        example: en-US
        required: false
        schema:
          type: string
          default: en-AU
      - name: cookieParam
        in: cookie
        description: Some cookie
        required: true
        schema:
          type: integer
          format: int64
