
openapi: 3.0.0
info:
  description:
    
    # Arquitectura de Información
    Proyecto Reconocimiento de Materiales de Iguala
  version: 1.0.0
  title: Arquitectura de Información RMI
  contact:
    name: Encargados de proyecto
    email: cvillegas@rimsamex.com
   
paths:
  /jobstory1:
      parameters:
        - name: archivoxml
          description: "Documento fiscal"
          required: true
          schema:
            type: file
